---
kind: 'pipeline'
name: 'default'
steps:
  - name: 'Lint code'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule lint'
      - 'molecule syntax'

  - name: 'Create test containers'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule cleanup'
      - 'molecule destroy'
      - 'molecule create'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  - name: 'Converge and verify'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule converge'
      - 'molecule idempotence'
      - 'molecule verify'

  - name: 'Cleanup'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule cleanup'
      - 'molecule destroy'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

volumes:
  - name: 'docker'
    host:
      path: '/var/run/docker.sock'
