---
kind: 'pipeline'
name: 'default'
steps:
  - name: 'Lint code'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule lint'
      - 'molecule syntax'

  - name: 'Create containers and converge'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule cleanup'
      - 'molecule destroy'
      - 'molecule create'
      - 'molecule converge'
      - 'molecule idempotence'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  - name: 'Verify result'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule verify'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  - name: 'Cleanup'
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule cleanup'
      - 'molecule destroy'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

volumes:
  - name: 'docker'
    host:
      path: '/var/run/docker.sock'

matrix:
  MOLECULE_DISTRO:
    - 'debian9'
    - 'debian8'
    - 'centos7'
    - 'centos6'
    - 'ubuntu1804'
    - 'ubuntu1604'
