---
pipeline:
  lint:
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule lint'
      - 'molecule syntax'

  converge:
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule cleanup'
      - 'molecule destroy'
      - 'molecule create'
      - 'molecule converge'
      - 'molecule idempotence'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  verify:
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule verify'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'

  cleanup:
    image: 'quay.io/ansible/molecule'
    commands:
      - 'molecule cleanup'
      - 'molecule destroy'
    privileged: True
    volumes:
      - name: 'docker'
        path: '/var/run/docker.sock'
    when:
      status:  [ 'failure', 'success' ]

matrix:
  MOLECULE_DISTRO:
    - 'debian9'
    - 'debian8'
    - 'centos7'
    - 'centos6'
    - 'ubuntu1804'
    - 'ubuntu1604'

volumes:
  - name: 'docker'
    host:
      path: '/var/run/docker.sock'
