---
pipeline:
  lint:
    image: quay.io/ansible/molecule
    commands:
      - 'molecule lint'
      - 'molecule syntax'

  test:
    image: quay.io/ansible/molecule
    commands:
      - 'molecule cleanup'
      - 'molecule --debug destroy'
      - 'molecule converge'
      - 'molecule idempotence'
      - 'molecule verify'
      - 'molecule cleanup'
      - 'molecule destroy'
    privileged: True
